# Generated by Django 5.0.6 on 2024-08-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_course_credits_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
