# Generated by Django 5.0.6 on 2024-08-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_module_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
